[features]
seeds = false
skip-lint = false
[programs.devnet]
chainlink_solana_dapp = "HQZi85hzkpTRQMqNXx9ehQNxy89TvjaDF3wxBv6SQU8v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
